package com.involuntaryminimalism.alerts.types;

import com.involuntaryminimalism.alerts.Alert;

/**
 * This type of alert is generated by nurses or patients triggering the alert button near their
 * beds.
 */
public class TriggeredAlert implements Alert {
  @Override
  public String getPatientId() {
    return "";
  }

  @Override
  public String getCondition() {
    return "";
  }

  @Override
  public long getTimestamp() {
    return 0;
  }
}
