package com.involuntaryminimalism.alerts.types;

import com.involuntaryminimalism.alerts.Alert;

/**
 * This type of alert is generated by nurses or patients triggering the alert button near their
 * beds.
 */
public class TriggeredAlert implements Alert {
  private final String patientId;
  private final String condition;
  private final long timestamp;

  protected TriggeredAlert(String patientId, String condition, long timestamp) {
    this.patientId = patientId;
    this.condition = condition;
    this.timestamp = timestamp;
  }

  public String getPatientId() {
    return patientId;
  }

  public String getCondition() {
    return condition;
  }

  public long getTimestamp() {
    return timestamp;
  }
}
