package com.involuntaryminimalism.data_management.inputs;


import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Handles reading data from a folder generated as output by this software.
 */
public class FileDataListener implements DataListener {

  private final Path baseFolder;

  public FileDataListener(Path baseFolder) {
    if ( Files.notExists(baseFolder)) {
      throw new IllegalArgumentException(
          "Given folder path does not exists:( \""+ baseFolder + "\""
      );
    }
    this.baseFolder = baseFolder;
  }

  /**
   * Parses all files in the base directory and returns content as described in the
   * DatListener contract.
   *
   * @throws IOException when problem with reading the files
   */
  @Override
  public List<String[]> readData() throws IOException {
    // collect all .txt files
    File[] files = baseFolder.toFile().listFiles(new FilenameFilter() {
      @Override
      public boolean accept(File dir, String name) {
        return name.toLowerCase().endsWith(".txt");
      }
    });

    // parse each file and accumulate their results
    var out = new ArrayList<String[]>();
    for (var file : files) {
      out.addAll(parseFile(file));
    }

    return out;

  }

  /**
   * Parses the content of a file generated by FileOutputStrategy into patient records.
   * @param file a file object that had been verified as valid and existing source (it
   *             is valid if the file was created by FileOutputStrategy)
   * @return list of records represented as described in the DatListener contract
   * @throws IOException
   */
  private List<String[]> parseFile(File file) throws IOException {
    var out = new ArrayList<String[]>();

    // parse entries line by line
    var br = new BufferedReader(new FileReader(file));
    String line;
    while ((line = br.readLine()) != null) {
      // Format: "Patient ID: %d, Timestamp: %d, Label: %s, Data: %s%n",
      String[] parts = line.strip().split(", ");

      // the separator is ":"
      String innerSeparator = ":";

      // convert line to standard form, for adapters
      out.add(
          new String[]{
              parts[0].split(innerSeparator)[1].strip(),  // patient ID
              parts[1].split(innerSeparator)[1].strip(),  // timestamp
              parts[2].split(innerSeparator)[1].strip(),  // label
              parts[3].split(innerSeparator)[1].strip(),  // data
          }
      );
    }

    return out;
  }
}
